services:
  pg:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=db_users
    volumes:
      - ./pgdata:/var/lib/postgresql/data