name: Java CI com Maven e Deploy via SSH

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
      broker_queue_email_name: "default.email"
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache do Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build do projeto
        run: mvn clean package -DskipTests

#      - name: Criar pasta app no servidor (caso não exista)
#        uses: appleboy/ssh-action@v0.1.9
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: 22
#          script: |
#            mkdir -p /home/ec2-user/app/

      - name: Limpar arquivo .jar antigo no servidor
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -f /home/ec2-user/target/agregate-0.0.1-SNAPSHOT.jar
            rm -rf /home/ec2-user/target


- name: Copiar arquivo .jar para o servidor via SCP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "target/agregate-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/"

#      - name: Executar comando remoto via SSH para reiniciar app
#        uses: appleboy/ssh-action@v0.1.9
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: 22
#          script: |
#            pkill -f agregate-0.0.1-SNAPSHOT.jar || true
#            echo "Reiniciando a aplicação..."
#            screen -dmS agregate java -jar /home/ec2-user/app/agregate-0.0.1-SNAPSHOT.jar

#      - name: Verificar últimos logs do app
#        uses: appleboy/ssh-action@v0.1.9
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: 22
#          script: |
#            echo "Últimas 50 linhas do log da aplicação:"
#            tail -n 50 /home/ec2-user/app/app.log
